### ISSUE TITLE
AccessDeniedError

### ISSUE THREAD

**Issue by ZachBenz** [ZachBenz/RingForIndigo#17]
From logs:

```
Traceback (most recent call last):
  File "plugin.py", line 127, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 308, in doorbells
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 287, in __devices
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 200, in query
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 113, in _get_oauth_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 71, in refresh_tokens
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
AccessDeniedError: (access_denied) token is invalid or does not exists

   Ring Error                      plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

My best guess is that this is the cached token expiring...

**Comment by ZachBenz** [comment]
Another type of AccessDeniedError:

```
Traceback (most recent call last):
  File "plugin.py", line 353, in validatePrefsConfigUi
  File "plugin.py", line 74, in makeConnectionToRing
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 64, in __init__
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 79, in _process_cached_session
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 130, in _authenticate
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 111, in _get_oauth_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 36, in fetch_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 67, in __fetch_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
AccessDeniedError: (access_denied) invalid user credentials
```

**Comment by ZachBenz** [comment]
v1.6.0
User on support forum experienced an unhandled AccessDeniedError:

```
Jan 2, 2020 at 4:52:09 PM
   Ring Error                      Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 181, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/generic.py", line 55, in update
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/generic.py", line 87, in _get_attrs
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 200, in query
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 113, in _get_oauth_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 71, in refresh_tokens
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
AccessDeniedError: (access_denied) token is invalid or does not exists

   Ring Error                      plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```
