### ISSUE TITLE
'key username not found in dict'

### ISSUE THREAD

**Issue by ZachBenz** [ZachBenz/RingForIndigo#2]
v1.0.0
From Indigo support forum:

Installed the plug and got a few errors after entering my username and password:[color=#FF0000] [quote]   Ring Error                      Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 107, in runConcurrentThread
KeyError: 'key username not found in dict'

   Ring Error                      plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by ZachBenz** [comment]
Able to reproduce this when clean installing on a production Indigo server:

```
Dec 28, 2019 at 3:40:27 PM
   Installing and enabling plugin Ring v1.0.1
   Loading plugin "Ring 1.0.1"
   Starting plugin "Ring 1.0.1" (pid 87866)
   Started plugin "Ring 1.0.1"
   Ring Error                      Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 107, in runConcurrentThread
KeyError: 'key username not found in dict'

   Ring Error                      plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Ring Error                      Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 107, in runConcurrentThread
KeyError: 'key username not found in dict'

   Ring Error                      plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Ring Error                      Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 107, in runConcurrentThread
KeyError: 'key username not found in dict'

   Ring Error                      plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Ring Debug                      Attempting to connect to Ring.com API and login as indigoguy@comcast.net
   Ring Debug                      Connection to Ring.com API successful
   Ring Debug                      Validated plugin configuration changes
   Ring Debug                      Connected to Ring.com API?: True
   Ring Debug                      Getting updates from Ring.com API
```

**Comment by ZachBenz** [comment]
Appears to be a startup timing/race condition/blocking issue of some kind.

**Comment by ZachBenz** [comment]
I think what is happening is: runConcurrentThread is firing (as it should), but since we're not configured yet, attempting to make use of a username field that doesn't yet exist.  Need to check to see if field even exists in dictionary, not just if it is blank/empty.
