### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by ZachBenz** [ZachBenz/RingForIndigo#23]
```
Ring Error                      Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 120, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 291, in doorbells
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 265, in __devices
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 183, in query
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 98, in _get_oauth_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 581, in post
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 533, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 646, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/adapters.py", line 498, in send
ConnectionError: ('Connection aborted.', error("(60, 'ETIMEDOUT')",))
```

**Comment by ZachBenz** [comment]
This isn't an oauthlib.oauth2.rfc6749.errors exception - it's a more generic one from requests/exceptions.py

**Comment by ZachBenz** [comment]
Another variant:

```
Traceback (most recent call last):
  File "plugin.py", line 176, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 308, in doorbells
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 282, in __devices
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 221, in query
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 546, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 533, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/sessions.py", line 646, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests/adapters.py", line 498, in send
ConnectionError: ('Connection aborted.', error("(54, 'ECONNRESET')",))
```

**Comment by ZachBenz** [comment]
Should at least catch it and have a user friendly error and/or debug message.
