### ISSUE TITLE
InvalidGrantError

### ISSUE THREAD

**Issue by ZachBenz** [ZachBenz/RingForIndigo#8]
As reported in Indigo support forum:

```
Ring Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
File "plugin.py", line 128, in runConcurrentThread
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/generic.py", line 56, in update
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/generic.py", line 103, in _get_health_attrs
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 200, in query
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 113, in _get_oauth_token
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 71, in refresh_tokens
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
InvalidGrantError: (invalid_grant) The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
```

**Comment by ZachBenz** [comment]
User only reported seeing this a single time (not a recurring error)

**Comment by ZachBenz** [comment]
User experienced error again:

```
29 Dec 2019 at 18:36:54
Ring Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
File "plugin.py", line 123, in runConcurrentThread
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 308, in doorbells
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 284, in __devices
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/generic.py", line 33, in __init__
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/generic.py", line 56, in update
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/generic.py", line 103, in _get_health_attrs
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 200, in query
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/__init__.py", line 113, in _get_oauth_token
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/ring_doorbell/auth.py", line 71, in refresh_tokens
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RingForIndigo.indigoPlugin/Contents/Server Plugin/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
InvalidGrantError: (invalid_grant) The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

Ring Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```
